### ISSUE TITLE
Bounding box description

### ISSUE THREAD

**Issue by simon-schaefer** [LeMuecke/mapcalc#2]
I noticed that the description of the bounding boxes in the Readme is in the wrong order. It says 

```
Boxes: A list of [x1, x2, y1, y2], each representing a box that was detected.
```

However, when we have a bounding box with corner (u, v) and shape (w, h), then the description should be: 

```
[u, v, u + w, v + h]
```

Maybe you could change it to make the usage more explicit :) Thank you, and generally very nice code :)

**Comment by klimaschkas** [comment]
I like the idea of describing the bounding box with corner and shape!
However, isn't a box then described as

```
[u, u + w, v, v + h]
```

So if we have the box

```
[10, 37, 17, 40]
```

then the variables would be u = 10, v = 17, w = 27, h = 23.

**Comment by simon-schaefer** [comment]
Thank you for the response, I'm glad you like the idea 😀 

Yes, but I think the order of box coordinates is mixed up in the current readme. 

In `main.py`, line 197-198 you are accessing the bounding boxes, and thereby determining the shape of the bbox as follows

```
iw = bi[2] - bi[0] + 1
ih = bi[3] - bi[1] + 1
```

Thus, the order should be (x1, y1, x2, y2). What do you think?

**Comment by klimaschkas** [comment]
Sorry for the late reply, I've been rather busy lately.

Yes, you are right! I'll update the documentation 🙂
